players = [{name: "Dušan",
			lastname: "Marković",
			number: 26,
			position: "Goalkeeper",
			age: 23,
			image: "D-Markovic.png"},
			{name: "Danijel",
			lastname: "Mićanović",
			number: 88,
			position: "Goalkeeper",
			age: 22,
			image: "D-Micanovic.png"},
			{name: "Marko",
			lastname: "Nikolić",
			number: 2,
			position: "Centre-back",
			age: 23,
			image: "M-Nikolic.png"},
			{name: "Miloš",
			lastname: "Tanović",
			number: 5,
			position: "Right-back",
			age: 25,
			image: "M-Tanovic.png"},
			{name: "Filip",
			lastname: "Kasalica",
			number: 9,
			position: "Left Winger",
			age: 33,
			image: "F-Kasalica.png"},
			{name: "Miloš",
			lastname: "Trifunović",
			number: 14,
			position: "Centre-forward",
			age: 37,
			image: "M-Trifunovic.png"},
			{name: "Aleksandar",
			lastname: "Busnić",
			number: 22,
			position: "Central Midfield",
			age: 24,
			image: "A-Busnic.png"},
			{name: "Dušan",
			lastname: "Živković",
			number: 27,
			position: "Attacking Midfield",
			age: 25,
			image: "D-Zivkovic.png"},
			{name: "Veljko",
			lastname: "Trifunović",
			number: 29,
			position: "Right Winger",
			age: 23,
			image: "V-Trifunovic.png"},
			{name: "Vanja",
			lastname: "Ilić",
			number: 55,
			position: "Right Winger",
			age: 22,
			image: "V-Ilic.png"},
			{name: "Vanja",
			lastname: "Ilić",
			number: 55,
			position: "Right Winger",
			age: 22,
			image: "V-Ilic.png"},
			{name: "Andrija",
			lastname: "Kaludjerović",
			number: 99,
			position: "Centre-forward",
			age: 34,
			image: "A-Kaludjerovic.png"},
			{name: "Uroš",
			lastname: "Damjanović",
			number: 8,
			position: "Attacking Midfield",
			age: 26,
			image: "U-Damjanovic.png"},
			{name: "Ostoja",
			lastname: "Stjepanović",
			number: 17,
			position: "Defensive Midfield",
			age: 36,
			image: "O-Stjepanovic.png"},
			{name: "Nemanja",
			lastname: "Petrović",
			number: 18,
			position: "Left-Back",
			age: 29,
			image: "N-Petrovic.png"},
			{name: "Ostoja",
			lastname: "Stjepanović",
			number: 17,
			position: "Defensive Midfield",
			age: 36,
			image: "O-Stjepanovic.png"}]